/** Wiki page titles of every building that has a Recipes table. */
export const BUILDING_TITLES = [
  'Apothecary',
  'Bakery',
  'Blacksmith',
  'Blast Furnace',
  'Cannery',
  'Carpenter',
  'Charcoal Furnace',
  'Chemist',
  'Coppersmith',
  'Cotton Gin',
  'Fine Kitchen',
  'Fishing Dock',
  'Flax Spinner',
  'Machinist',
  'Mill',
  'Netter',
  'Oil Press',
  'Ore Furnace',
  'Sawmill',
  'Sifting Tower',
  'Smokery',
  'Soup Kitchen',
  'Spice Grinder',
  'Stone Cutter',
  'Tailor',
  'Tea Roaster',
  'Weaver',
]
